### ISSUE TITLE
Needs solutions

### ISSUE THREAD

**Issue by bhuvan-venkatesh** [illinois-cs241/handouts#16]
Each worksheet and slide pair need solutions and teaching explanation

**Comment by bchong95** [comment]
Bonus points creating a build system to put those solutions in the plaintext source and have a flag to generate a TA version. Similar to David's magic ifdef process for assignments.

**Comment by bhuvan-venkatesh** [comment]
Eventually referencing #15 

We can use http://pandoc.org/scripting.html and create a custom filter/non filtered version if pandoc is the final choice (which I think it should be)

**Comment by bhuvan-venkatesh** [comment]
Build system in place with a makefile 
262a095b584ec070bd820a7d90bddb200248560b

It is almost the same as David's magic ifdef except this filters.
`make worksheet` will make student
`make solution` will make ta solution

The markdown has a pretty lightweight way (which we can change easily) of getting this done

> solution:
>    this is the solution
>    unfortunately it has to be one paragraph -
>    Because the AST for this would be hard to 
>    Walk if there were multiple paragraphs 
>    (can be changed with advanced parsing but lazy right now)
> else:
>    Put in as many line breaks as you need to make the document
>    look pretty
> \
> \
> \
